name: mocritic_new
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - beautifulsoup4
  - blas
  - brotlipy
  - ca-certificates
  - catalogue
  - certifi
  - cffi
  - charset-normalizer
  - click
  - colorama
  - cryptography
  - cudatoolkit
  - cycler
  - cymem
  - cython-blis
  - dbus
  - expat
  - fftw
  - filelock
  - fontconfig
  - freetype
  - gdown
  - giflib
  - glib
  - gst-plugins-base
  - gstreamer
  - h5py
  - hdf5
  - icu
  - idna
  - importlib-metadata
  - intel-openmp
  - jinja2
  - joblib
  - jpeg
  - kiwisolver
  - langcodes
  - lcms2
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - libpng
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libuv
  - libwebp
  - libxcb
  - libxml2
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - murmurhash
  - ncurses
  - ninja
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pathy
  - pcre
  - pillow
  - pip
  - preshed
  - pycparser
  - pydantic
  - pyopenssl
  - pyparsing
  - pyqt
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - qt
  - readline
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - shellingham
  - sip
  - six
  - smart_open
  - soupsieve
  - spacy
  - sqlite
  - threadpoolctl
  - tk
  - tornado
  - tqdm
  - trimesh
  - typer
  - wheel
  - xz
  - zipp
  - zlib
  - zstd
  - pip:
      - blobfile
      - cachetools
      - chumpy
      - docker-pycreds
      - flask
      - freetype-py
      - ftfy
      - gitdb
      - gitpython
      - imageio
      - imageio-ffmpeg
      - itsdangerous
      - lxml
      - mapbox-earcut
      - networkx
      - nvidia-ml-py
      - nvitop
      - opencv-python
      - pandas
      - platformdirs
      - protobuf
      - psutil
      - pycryptodomex
      - pyglet
      - pyopengl
      - pyrender
      - pytorch-warmup
      - pytz
      - pyyaml
      - regex
      - seaborn
      - sentry-sdk
      - setproctitle
      - shapely
      - smmap
      - smplx
      - srsly
      - termcolor
      - typing-extensions
      - urllib3
      - wandb
      - wasabi
      - wcwidth
      - werkzeug
      - clip
      - pytorch3d
      - torchsort